CREATE TABLE Addresses (
	Id INT IDENTITY(1,1) NOT NULL,
	AddressLine1 VARCHAR(255) NOT NULL,
	AddressLine2 VARCHAR(255) NOT NULL,
	PostalCode VARCHAR(10) NOT NULL,
	City VARCHAR(255) NOT NULL,
	Country VARCHAR(255) NOT NULL,
	PRIMARY KEY (Id)
)

CREATE TABLE Libraries (
	Id INT IDENTITY(1,1) NOT NULL,
	[Name] VARCHAR(255) NOT NULL,
	AddressId INT NOT NULL,
	PRIMARY KEY (Id),
	FOREIGN KEY (AddressId) REFERENCES Addresses (Id)
)

CREATE TABLE ItemTypes (
	Id INT NOT NULL,
	[Type] VARCHAR(255) NOT NULL,
	PRIMARY KEY (Id),
)

CREATE TABLE Items (
	Id INT IDENTITY(1,1) NOT NULL,
	Isbn VARCHAR(255) NOT NULL,
	Title VARCHAR(255) NOT NULL,
    [Description] VARCHAR(255) NOT NULL,
	TypeId INT NOT NULL,
	[LibraryId] INT NOT NULL,
	PRIMARY KEY (Id),
	FOREIGN KEY (LibraryId) REFERENCES Libraries (Id),
	FOREIGN KEY (TypeId) REFERENCES ItemTypes (Id)
)

CREATE TABLE Authors (
	Id INT IDENTITY(1,1) NOT NULL,
	FirstName VARCHAR(255) NOT NULL,
	LastName VARCHAR(255) NOT NULL,
	PRIMARY KEY (Id)
)

CREATE TABLE Books (
	Id INT IDENTITY (1,1) PRIMARY KEY,
    IsLeased BIT DEFAULT(0) NOT NULL,
	FOREIGN KEY (Id) REFERENCES Items (Id)
)

CREATE TABLE AuthorItems (
	AuthorId INT NOT NULL,
	ItemId INT NOT NULL,
	PRIMARY KEY (AuthorId, ItemId),
	FOREIGN KEY (AuthorId) REFERENCES Authors (Id),
	FOREIGN KEY (ItemId) REFERENCES Items (Id),
)

CREATE TABLE DesiredItems (
	Id INT PRIMARY KEY,
	Reason VARCHAR(MAX),
	FOREIGN KEY (Id) REFERENCES Items (Id)
)

CREATE TABLE Persons (
	Ssn VARCHAR(20) UNIQUE NOT NULL,
	Email VARCHAR(255) NOT NULL,	
	PhoneNumber VARCHAR(255) NOT NULL,
	PRIMARY KEY (Ssn)
)

CREATE TABLE EmployeePositions (
	Id INT IDENTITY(1,1) NOT NULL,
	[Name] VARCHAR(255) NOT NULL,
	PRIMARY KEY (Id)
)

CREATE TABLE Employees (
	Ssn VARCHAR(20) PRIMARY KEY,
	AddressId INT NOT NULL,
	EmployeePositionId INT NOT NULL,
	FOREIGN KEY (Ssn) REFERENCES Persons (Ssn),
	FOREIGN KEY (AddressId) REFERENCES Addresses (Id),
	FOREIGN KEY (EmployeePositionId) REFERENCES EmployeePositions (Id)
)

CREATE TABLE Campuses (
	Id INT IDENTITY(1,1) PRIMARY KEY,
	[Name] VARCHAR(255) NOT NULL,
	AddressId INT NOT NULL,
	FOREIGN KEY (AddressId) REFERENCES Addresses (Id)
)

CREATE TABLE Members (
	Ssn VARCHAR(20) PRIMARY KEY,
	CardValidity DATETIME NOT NULL,
	CampusId INT NOT NULL,
	FOREIGN KEY (Ssn) REFERENCES Persons (Ssn),
	FOREIGN KEY (CampusId) REFERENCES Campuses (Id)
)

CREATE TABLE Leases (
	Id INT IDENTITY(1,1) PRIMARY KEY,
	DateOfIssue DateTime NOT NULL,
	DateOfReturn DateTime NOT NULL,
	DateReturned DateTime,
	MemberSsn VARCHAR(20) NOT NULL,
	BookId INT NOT NULL,
	FOREIGN KEY (MemberSsn) REFERENCES Members (Ssn),
	FOREIGN KEY (BookId) REFERENCES Books (Id)
)